using Grafted.Sim.Entities;
using Grafted.Sim.Entities.Pawns.Modifiers;

namespace Grafted.Sim.Combat;

public static class CombatHelpers
{
    public static DamageRequest CalculateDamages(Pawn pawn, Item tool)
    {
        var pawnStrength = pawn.GetStatValue(Defs.Stats.MeleeStrength);
        var toolPower = tool.GetStatValue(Defs.Stats.MeleePower);
        var toolManeuver = tool.ItemDef.WeaponProperties!.WeaponManeuvers.RandomElement();
        var skillPower = 1 + (pawn.GetSkill(tool.ItemDef.WeaponProperties!.WeaponType)?.Level * .1f ?? 0);
        var rawDamage = Mathf.RoundToInt(
            toolPower
            * pawnStrength
            * skillPower
            * toolManeuver.DamageMultiplier.RandomValue
        );
        //rawDamage *= tool.GetStatValue(Defs.Stats.WeaponDamageMultiplier);
        if (rawDamage < 0)
        {
            Log.Warning("Damage was negative.");
            rawDamage = 0;
        }

        DamageRequest request = new(pawn, tool, toolManeuver);
        request.RawDamages.Add(new Damage(tool, rawDamage));

        return request;
    }
}

public class Damage(Item tool, double amount)
{
    public readonly Item Tool = tool;
    public WeaponType WeaponType => Tool.ItemDef.WeaponProperties!.WeaponType;
    public DamageType Type => Tool.ItemDef.WeaponProperties!.DamageType;

    public List<BodyPartModifierRecord> BodyPartModifiers =>   Tool.ItemDef.WeaponProperties?.BodyPartModifiers
        // Join modifiers list from enchantments
        .Concat(Tool.Enchantments?.Where(e => e.ItemDef.WeaponProperties != null).SelectMany(e => e.ItemDef.WeaponProperties!.BodyPartModifiers) ?? []).ToList() ?? [];

    // Total damage generated by tool
    public readonly double TotalDamage = amount;

    // TotalDamage minus the blocked amount
    public double TotalUnblockedDamage { get; private set; } = amount;

    public void Block(Item equipment)
    {
        TotalUnblockedDamage = Math.Clamp(TotalDamage - equipment.GetStatValue(Defs.Stats.PhysicalResistance), 0, TotalDamage);
    }
}

public class DamageRequest
{
    public readonly Pawn Source;
    public Item Weapon { get; }
    public List<Damage> RawDamages = new(1);
    public List<DamageRecord> TrinketResults { get; private set; } = [];
    public WeaponManeuverDef WeaponManeuver { get; }

    public double TotalRawDamage => RawDamages.Sum(damage => damage.TotalDamage);

    public DamageRequest(Pawn source, Item weapon, WeaponManeuverDef weaponManeuver)
    {
        WeaponManeuver = weaponManeuver;
        Source = source;
        Weapon = weapon;
    }

    public void AddTrinketResults(List<DamageRecord>? trinketResults)
    {
        TrinketResults = trinketResults ?? [];
    }
}

public class DamageResponse
{
    public readonly List<DamageRecord> Damages = new();
    public readonly List<DamageRecord> TrinketDamages = new();

    public bool Dodged;
    public bool Missed;
}

public class AfflictionRecord(BodyPart bodyPart, string label)
{
    public readonly BodyPart BodyPart = bodyPart;
    public readonly string Label = label;
}

public class DestroyedItemRecord
{
    public readonly ItemDef Def;

    public DestroyedItemRecord(ItemDef def)
    {
        Def = def;
    }
}

public class DamageRecord
{
    public readonly string WeaponLabel;
    public readonly string WeaponManeuverLabel;
    public readonly DamageType DamageType;
    public readonly BodyPart BodyPartHit;
    public readonly List<AfflictionRecord> SourceAfflictions = [];
    public IReadOnlyList<DamagedBodyPartRecord> BodyParts = new List<DamagedBodyPartRecord>();
    public readonly List<DestroyedItemRecord> DestroyedEquipment = [];
    public readonly double TotalDamage;
    public double ActualAmount;

    public DamageRecord(string weaponLabel, string weaponManeuverLabel, DamageType damageType, BodyPart bodyPartHit, double totalDamage)
    {
        WeaponLabel = weaponLabel;
        WeaponManeuverLabel = weaponManeuverLabel;
        DamageType = damageType;
        BodyPartHit = bodyPartHit;
        TotalDamage = totalDamage;
    }

    public double AmountBlocked => TotalDamage - ActualAmount;
}

public class DamagedBodyPartRecord
{
    public readonly BodyPart BodyPart;
    public double DamageApplied;
    public string Label => BodyPart.Label;
    public List<BodyPartModifierDef> AppliedModifiers = new();
    public BodyPartType PartType => BodyPart.Type;
    public bool WasDestroyed;
    public bool StoppedFunctioning;
    public bool WasSevered;
    public bool IsVital => BodyPart.IsVital;

    public DamagedBodyPartRecord(BodyPart bodyPart, double damageApplied = 0)
    {
        BodyPart = bodyPart;
        DamageApplied = damageApplied;
    }
}