using Grafted.Sim.Entities;

namespace Grafted.Sim.Combat;

public static class CombatHelpers
{
    public static DamageRequest CalculateDamages(Pawn pawn, Item tool)
    {
        var pawnStrength = pawn.GetStatValue(Defs.Stats.MeleeStrength);
        var toolPower = tool.GetStatValue(Defs.Stats.MeleePower);
        var toolManeuver = tool.ItemDef.ToolManeuvers.RandomElement();
        var skillPower = 1 + (pawn.GetSkill(tool.ItemDef.ToolType)?.Level * .1f ?? 0);
        var rawDamage = Mathf.RoundToInt(
            toolPower
            * pawnStrength
            * skillPower
            * toolManeuver.DamageMultiplier.RandomValue
        );
        //rawDamage *= tool.GetStatValue(Defs.Stats.WeaponDamageMultiplier);
        if (rawDamage < 0)
        {
            Log.Warning("Damage was negative.");
            rawDamage = 0;
        }

        DamageRequest request = new(pawn, tool, toolManeuver);
        request.RawDamages.Add(new Damage(tool, rawDamage));

        return request;
    }
}

public class Damage(Item tool, float amount)
{
    public readonly Item Tool = tool;
    public ToolType ToolType => Tool.ItemDef.ToolType;
    public DamageType Type => Tool.ItemDef.WeaponProperties.DamageType;

    public List<BodyPartModifierRecord> BodyPartModifiers => Tool.ItemDef.WeaponProperties.BodyPartModifiers;

    // Total damage generated by tool
    public readonly float TotalDamage = amount;

    // TotalDamage minus the blocked amount
    public float TotalUnblockedDamage { get; private set; } = amount;

    public void Block(Item equipment)
    {
        TotalUnblockedDamage = Mathf.Clamp(TotalDamage - equipment.GetStatValue(Defs.Stats.PhysicalResistance), 0, TotalDamage);
    }
}

public class DamageRequest
{
    public readonly Pawn Source;
    public Item Tool { get; }
    public List<Damage> RawDamages = new(1);

    public ToolManeuverDef ToolManeuver { get; }

    public float TotalRawDamage => RawDamages.Sum(damage => damage.TotalDamage);

    public DamageRequest(Pawn source, Item tool, ToolManeuverDef toolManeuver)
    {
        ToolManeuver = toolManeuver;
        Source = source;
        Tool = tool;
    }
}

public class DamageResponse
{
    public List<DamageRecord> Damages = new();

    public bool Dodged;
    public bool Missed;

    public DamageResponse()
    {
    }
}

public class DestroyedItemRecord
{
    public readonly ItemDef Def;

    public DestroyedItemRecord(ItemDef def)
    {
        Def = def;
    }
}

public class DamageRecord
{
    public readonly DamageType DamageType;
    public readonly BodyPart BodyPartHit;
    public IReadOnlyList<DamagedBodyPartRecord> BodyParts = new List<DamagedBodyPartRecord>();
    public List<DestroyedItemRecord> DestroyedEquipment = new();
    public readonly float TotalDamage;
    public float ActualAmount;

    public DamageRecord(DamageType damageType, BodyPart bodyPartHit, float totalDamage)
    {
        DamageType = damageType;
        BodyPartHit = bodyPartHit;
        TotalDamage = totalDamage;
    }

    public float AmountBlocked => TotalDamage - ActualAmount;
}

public class DamagedBodyPartRecord
{
    public readonly BodyPart BodyPart;
    public float DamageApplied;
    public string Label => BodyPart.Label;
    public List<BodyPartModifierDef> AppliedModifiers = new();
    public BodyPartType PartType => BodyPart.Type;
    public bool WasDestroyed;
    public bool StoppedFunctioning;
    public bool WasSevered;
    public bool IsVital => BodyPart.IsVital;

    public DamagedBodyPartRecord(BodyPart bodyPart, float damageApplied = 0)
    {
        BodyPart = bodyPart;
        DamageApplied = damageApplied;
    }
}