using Grafted.Sim.Entities;
using Grafted.Sim.Entities.Pawns;
using Grafted.Sim.Entities.Pawns.Modifiers;

namespace Grafted.Sim.Combat;

public class Damage(Item weapon, double amount, string weaponManeuver)
{
    public readonly Item Weapon = weapon;
    public readonly string WeaponManeuver = weaponManeuver;
    public WeaponType WeaponType => Weapon.ItemDef.WeaponProperties!.WeaponType;
    public DamageType Type => Weapon.ItemDef.WeaponProperties?.DamageType
    ?? Weapon.ItemDef.AmmoProperties?.DamageType
    ?? DamageType.Invalid;

    public List<BodyPartModifierRecord> BodyPartModifiers => Weapon.ItemDef.WeaponProperties?.BodyPartModifiers
        // Join modifiers list from enchantments
        .Concat(Weapon.Enchantments?.Where(e => e.ItemDef.EnchantmentProperties != null).SelectMany(e => e.ItemDef.EnchantmentProperties!.BodyPartModifiers) ?? []).ToList() ?? [];

    // Total damage generated by tool
    public readonly double TotalDamage = amount;

    // TotalDamage minus the blocked amount
    public double TotalUnblockedDamage { get; private set; } = amount;

    public float GetSubstanceModifier(SubstanceType substance) => Weapon.ItemDef.WeaponProperties?.GetSubstanceModifier(substance) ?? 1f;

    public void Block(Item equipment)
    {
        TotalUnblockedDamage = Math.Clamp(TotalDamage - equipment.GetStatValue(Defs.Stats.PhysicalResistance), 0, TotalDamage);
    }
}