namespace Wendlewind.Sim.Combat;

public class Damage
{
    public readonly Item Weapon;
    public readonly string WeaponManeuver;
    public readonly bool IsCritical;
    public WeaponType WeaponType => Weapon.ItemDef.WeaponProperties!.WeaponType;

    public Damage(Item weapon, double amount, string weaponManeuver, bool isCritical = false)
    {
        Weapon = weapon;
        TotalDamage = amount;
        TotalUnblockedDamage = amount;
        WeaponManeuver = weaponManeuver;
        IsCritical = isCritical;
    }

    // Overload for trinket damage with a label (non-critical)
    public Damage(Item weapon, double amount, string weaponManeuver) : this(weapon, amount, weaponManeuver, false) { }
    public DamageType Type => Weapon.ItemDef.WeaponProperties?.DamageType
    ?? Weapon.ItemDef.AmmoProperties?.DamageType
    ?? DamageType.Invalid;

    public List<BodyPartModifierRecord> BodyPartModifiers => Weapon.ItemDef.WeaponProperties?.BodyPartModifiers
        // Join modifiers list from enchantments
        .Concat(Weapon.Enchantments?.Where(e => e.ItemDef.EnchantmentProperties != null).SelectMany(e => e.ItemDef.EnchantmentProperties!.BodyPartModifiers) ?? []).ToList() ?? [];

    // Total damage generated by tool
    public readonly double TotalDamage;

    // TotalDamage minus the blocked amount
    public double TotalUnblockedDamage { get; private set; }

    public float GetSubstanceModifier(SubstanceType substance) => Weapon.ItemDef.WeaponProperties?.GetSubstanceModifier(substance) ?? 1f;

    public void Block(Item equipment)
    {
        TotalUnblockedDamage = Math.Clamp(TotalDamage - equipment.GetStatValue(Defs.Stats.PhysicalResistance), 0, TotalDamage);

        var damageBlocked = TotalDamage - TotalUnblockedDamage;
        var durabilityLossFactor = equipment.Context.Rng.NextFloat(0.2f, 0.5f);
        var durabilityLoss = (float)(damageBlocked * durabilityLossFactor);

        equipment.ApplyDurabilityLoss(durabilityLoss);
    }
}