<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Wendlewind.Server</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wendlewind.Simulation\Wendlewind.Simulation.csproj" />
    <ProjectReference Include="..\Wendlewind.NetCode\Wendlewind.NetCode.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Wendlewind\Content\Data\**\*">
      <Link>Content\Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

