// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Linq;
global using FontStashSharp;
global using Wendlewind.Debug;
global using Wendlewind.Definitions;
global using Wendlewind.Maths;
global using Wendlewind.Scenes.MainGameScene.Gui.Widgets;
global using Wendlewind.Scenes.MainGameScene.Gui.Widgets.CombatWidgets;
global using Wendlewind.Scenes.MainGameScene.Gui.Widgets.Grimoire;
global using Wendlewind.Scenes.MainGameScene.Gui.Widgets.MiscWidgets;
global using Wendlewind.Scenes.MainGameScene.Gui.Widgets.PawnRenderer;
global using Wendlewind.Sim;
global using Wendlewind.Sim.LootBoxes;
global using Wendlewind.Sim.Achievements;
global using Wendlewind.Sim.Combat;
global using Wendlewind.Sim.Entities;
global using Wendlewind.Sim.Entities.Items;
global using Wendlewind.Sim.Entities.Pawns;
global using Wendlewind.Sim.Entities.Pawns.Bodies;
global using Wendlewind.Sim.Entities.Pawns.Modifiers;
global using Wendlewind.Sim.Entities.Items.Enchantments;
global using Wendlewind.Sim.Entities.Items.Equipment;
global using Wendlewind.Sim.Entities.Items.Medicinals;
global using Wendlewind.Sim.Entities.Items.Potions;
global using Wendlewind.Sim.Entities.Items.Trinkets;

global using Wendlewind.Sim.Persistence;
global using Wendlewind.Sim.Zones;
global using Wendlewind.PawnLayout;
global using Wendlewind.Presentation;
global using Wendlewind.Utils;
global using JetBrains.Annotations;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Myra.Graphics2D;
global using Myra.Graphics2D.TextureAtlases;
global using Myra.Graphics2D.UI;
global using Myra.Graphics2D.UI.Styles;
global using Myra.Graphics2D.Brushes;
global using HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment;
global using Keys = Microsoft.Xna.Framework.Input.Keys;
global using Label = Myra.Graphics2D.UI.Label;