namespace Wendlemire.Sim.Combat;

public class Damage
{
    public readonly Item Weapon;
    public readonly string WeaponManeuver;
    public readonly bool IsCritical;
    private readonly float _magic;
    private List<BodyPartModifierRecord>? _bodyPartModifiers;
    public WeaponType WeaponType => Weapon.ItemDef.WeaponProperties!.WeaponType;

    public Damage(Item weapon, double amount, string weaponManeuver, bool isCritical = false, float magic = 1f)
    {
        Weapon = weapon;
        TotalDamage = amount;
        TotalUnblockedDamage = amount;
        WeaponManeuver = weaponManeuver;
        IsCritical = isCritical;
        _magic = magic;
    }

    // Overload for trinket damage with a label (non-critical)
    public Damage(Item weapon, double amount, string weaponManeuver) : this(weapon, amount, weaponManeuver, false) { }
    public DamageType Type => Weapon.ItemDef.WeaponProperties?.DamageType
    ?? Weapon.ItemDef.AmmoProperties?.DamageType
    ?? DamageType.Invalid;

    public List<BodyPartModifierRecord> BodyPartModifiers
    {
        get
        {
            if (_bodyPartModifiers != null)
            {
                return _bodyPartModifiers;
            }

            _bodyPartModifiers = [];
            var weaponMods = Weapon.ItemDef.WeaponProperties?.BodyPartModifiers;
            if (weaponMods != null)
            {
                _bodyPartModifiers.AddRange(weaponMods);
            }

            if (Weapon.Enchantments == null)
            {
                return _bodyPartModifiers;
            }

            foreach (var enchantment in Weapon.Enchantments)
            {
                var properties = enchantment.ItemDef.EnchantmentProperties;
                var enchantmentMods = properties?.BodyPartModifiers;
                if (enchantmentMods == null)
                {
                    continue;
                }

                foreach (var record in enchantmentMods)
                {
                    _bodyPartModifiers.Add(properties!.ScaleRecord(record, _magic));
                }
            }

            return _bodyPartModifiers;
        }
    }

    // Total damage generated by tool
    public readonly double TotalDamage;

    // TotalDamage minus the blocked amount
    public double TotalUnblockedDamage { get; private set; }

    public float GetSubstanceModifier(SubstanceType substance) => Weapon.ItemDef.WeaponProperties?.GetSubstanceModifier(substance) ?? 1f;

    public void Block(Item equipment)
    {
        var resist = equipment.GetStatValue(Defs.Stats.PhysicalResistance);
        var reduction = CombatBalance.ArmorReduction(resist);
        TotalUnblockedDamage = Math.Clamp(TotalDamage * (1.0 - reduction), 0, TotalDamage);

        var damageBlocked = TotalDamage - TotalUnblockedDamage;
        var durabilityLossFactor = equipment.Context.Rng.NextFloat(0.2f, 0.5f);
        var durabilityLoss = (float)(damageBlocked * durabilityLossFactor);

        equipment.ApplyDurabilityLoss(durabilityLoss);
    }
}